export const Recommendations = [
    {
        theme: "#186A64",
        iconTheme: "#186A64",
        iconName: "LiaCubesSolid",
        iconSize: "text-2xl",
        bgSize: "40px",
        gradient: "linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,.05))",
        title: "Design Workshop Facilitation",
        summary: "Master your skills in design workshop facilitation and learn how to promote collaboration and find...",
        category: "Advanced",
        duration: 6,
        rating: 4.9,
        ratingAmmount: 1980,
    },
    {
        theme: "#FFBD4C",
        iconTheme: "#00000030",
        iconName: "LiaNeos",
        iconSize: "text-2xl",
        bgSize: "40px",
        gradient: "linear-gradient(to top, rgba(0,0,0,.3), rgba(255,255,255,.05))",
        title: "Animation for Beginners",
        summary: "Master your skills in design workshop facilitation and learn how to promote collaboration and find...",
        category: "Beginner",
        duration: 6,
        rating: 4.9,
        ratingAmmount: 1980,
    },
    {
        theme: "#106B97",
        iconTheme: "#39D0FB",
        iconName: "LiaHornbill",
        iconSize: "text-2xl",
        bgSize: "40px",
        gradient: "linear-gradient(to top, rgba(255,255,255,.3), rgba(255,255,255,.05))",
        title: "Common Design Patterns",
        summary: "Master your skills in design workshop facilitation and learn how to promote collaboration and find...",
        category: "Intermediate",
        duration: 6,
        rating: 4.9,
        ratingAmmount: 1980,
    },
    {
        theme: "#926CFD",
        iconTheme: "#00000030",
        iconName: "LiaDungeonSolid",
        iconSize: "text-2xl",
        bgSize: "40px",
        gradient: "linear-gradient(to top, rgba(0,0,0,.3), rgba(255,255,255,.05))",
        title: "3D Design Foundation",
        summary: "Master your skills in design workshop facilitation and learn how to promote collaboration and find...",
        category: "Beginner",
        duration: 6,
        rating: 4.9,
        ratingAmmount: 1980,
    },
    {
        theme: "#16161E",
        iconTheme: "#FFFFFF30",
        iconName: "LiaSlack",
        iconSize: "text-2xl",
        bgSize: "40px",
        gradient: "linear-gradient(to top, rgba(0,0,0,.3), rgba(255,255,255,.05))",
        title: "Framer for Beginner",
        summary: "Master your skills in design workshop facilitation and learn how to promote collaboration and find...",
        category: "Beginner",
        duration: 6,
        rating: 4.9,
        ratingAmmount: 1980,
    },
    {
        theme: "#FF784B",
        iconTheme: "#00000030",
        iconName: "LiaDelicious",
        iconSize: "text-2xl",
        bgSize: "40px",
        gradient: "linear-gradient(to top, rgba(0,0,0,.3), rgba(255,255,255,.05))",
        title: "Design Workshop Facilitation",
        summary: "Master your skills in design workshop facilitation and learn how to promote collaboration and find...",
        category: "Beginner",
        duration: 6,
        rating: 4.9,
        ratingAmmount: 1980,
    },

]